# YAML file to be used with VSTS CI. The orchestration of build app, test app, and 
# create docker image happens through the steps defined here.
# See http://docs.microsoft.com/vsts/pipelines/languages/docker for more information
variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*[Tt]ests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '--configuration $(buildConfiguration) --output out'
      zipAfterPublish: false

  - script: docker build -f Dockerfile -t adventworks/dotnetcore-sample .