# Build Docker image for this app
# http://docs.microsoft.com/vsts/pipelines/languages/docker?view=vsts
queue: Hosted Linux Preview
variables:
  buildConfiguration: 'Release'
  dockerId: adventworks  # change this to match your Docker Id

steps:
- script: dotnet build --configuration $(buildConfiguration)
- script: dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx
- script: dotnet publish --configuration $(buildConfiguration) --output out
- script: docker build -t $(dockerId)/dotnetcore-sample:$BUILD_BUILDID .
- script: |
    docker login -u $(dockerId) -p $(dockerPassword) |
    docker push $(dockerId)/dotnetcore-sample:$BUILD_BUILDID
    
- script: |
    docker-compose -f docs/docker-compose.yml --project-directory . -p docs up -d |
    docker wait docs_sut_1 |
    docker-compose -f docs/docker-compose.yml --project-directory . down
